// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDf6l9-h5EgP-TFvTqbxMWOPdDtlee3Zdg',
    appId: '1:902110224090:web:6ec7b69204bc1cd4034fe3',
    messagingSenderId: '902110224090',
    projectId: 'serviceproject-91b26',
    authDomain: 'serviceproject-91b26.firebaseapp.com',
    storageBucket: 'serviceproject-91b26.firebasestorage.app',
    measurementId: 'G-381DVEV5KJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1pP12BEcJyAc7wJSV8X9d0vR-GJ6yxPA',
    appId: '1:902110224090:android:5a818533a55760d8034fe3',
    messagingSenderId: '902110224090',
    projectId: 'serviceproject-91b26',
    storageBucket: 'serviceproject-91b26.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNt7LsDj7CsUS8y2CAn8sk1s3DamepbD4',
    appId: '1:902110224090:ios:005a7a58fddfb678034fe3',
    messagingSenderId: '902110224090',
    projectId: 'serviceproject-91b26',
    storageBucket: 'serviceproject-91b26.firebasestorage.app',
    iosBundleId: 'com.example.service',
  );
}
